### ISSUE TITLE
Console spam NPE with waila

### ISSUE THREAD

**Issue by LemADEC** [The-Fireplace/Overlord#142]
As of Overlord-1.12.2-2.4.10 + Hwyla-1.8.26-B41_1.12.2, console gets spammed when players are looking at a SkelletonMaker:
```
[07:07:08] [Server thread/FATAL] [VF]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
>       at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
>       at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
>       at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3422]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3972) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
>       at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
>       at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:72) ~[FluidStack.class:?]
>       at the_fireplace.overlord.tileentity.TileEntitySkeletonMaker.getTankProperties(TileEntitySkeletonMaker.java:421) ~[TileEntitySkeletonMaker.class:?]
>       at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:61) ~[HUDHandlerTank.class:?]
>       at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
>       at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
>       ... 7 more
```

Relevant code is here https://github.com/The-Fireplace-Minecraft-Mods/Overlord/blob/f6f8cef53ca87fefba9ffd1a30fe8e7155056d29/src/main/java/the_fireplace/overlord/tileentity/TileEntitySkeletonMaker.java#L420
From a quick code review:
- when milk is present, the FluidStack is "created" twice.
- when no milk is present, getFluid() returns null which crashes the FluidStack constructor.

**Comment by Neglevin** [comment]
I'm having this issue as well: https://paste.dimdev.org/umusehoyac.mccrash

**Comment by Neglevin** [comment]
I'm having this same problem as well: https://paste.dimdev.org/heyazugohi.mccrash
